/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatserverdesktop;

import midlewareDesktop.ChatServerDesktop;
import midlewareWeb.ChatServerWeb;

/**
 *
 * @author leonardo
 */
public class controlPanel extends javax.swing.JFrame {

    /**
     * Creates new form controlPanel
     */
    public controlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do 
     * NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWebClient = new javax.swing.JLabel();
        lblDesktopClient = new javax.swing.JLabel();
        lblAdvertisiment = new javax.swing.JLabel();
        btnTurnOnDesktop = new javax.swing.JToggleButton();
        btnAdvertisement = new javax.swing.JToggleButton();
        btnTurnOnWeb = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWebClient.setText("Server for Web Client: ");

        lblDesktopClient.setText("Server for Desktop client:");

        lblAdvertisiment.setText("Advertisement:");

        btnTurnOnDesktop.setText("Turn On");
        btnTurnOnDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnOnDesktopActionPerformed(evt);
            }
        });

        btnAdvertisement.setText("Turn On");
        btnAdvertisement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvertisementActionPerformed(evt);
            }
        });

        btnTurnOnWeb.setText("Turn On");
        btnTurnOnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnOnWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDesktopClient)
                    .addComponent(lblAdvertisiment, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWebClient, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdvertisement, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTurnOnDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTurnOnWeb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebClient)
                    .addComponent(btnTurnOnWeb))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesktopClient)
                    .addComponent(btnTurnOnDesktop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdvertisiment)
                    .addComponent(btnAdvertisement))
                .addContainerGap(448, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnOnDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnOnDesktopActionPerformed
        if(btnTurnOnWeb.isSelected()){
            ChatServerDesktop server = new ChatServerDesktop();
            server.startServerDesktop();
            btnTurnOnDesktop.setText("Turn Off");
        }
        else{
            btnTurnOnDesktop.setText("Turn On");
        }
    }//GEN-LAST:event_btnTurnOnDesktopActionPerformed

    private void btnAdvertisementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvertisementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdvertisementActionPerformed

    private void btnTurnOnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnOnWebActionPerformed
        if(btnTurnOnWeb.isSelected()){
            ChatServerWeb server = new ChatServerWeb();
            server.startServerWeb();
            btnTurnOnWeb.setText("Turn Off");
        }
        else{
            btnTurnOnWeb.setText("Turn On");
        }
    }//GEN-LAST:event_btnTurnOnWebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new controlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdvertisement;
    private javax.swing.JToggleButton btnTurnOnDesktop;
    private javax.swing.JToggleButton btnTurnOnWeb;
    private javax.swing.JLabel lblAdvertisiment;
    private javax.swing.JLabel lblDesktopClient;
    private javax.swing.JLabel lblWebClient;
    // End of variables declaration//GEN-END:variables
}
